apiVersion: v1
kind: Pod
metadata:
  name: busybox-test
  namespace: web-app
  labels:
    app: busybox

spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "while true; do echo running; sleep 5; done"]
