apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/shiva00077/k8s-nginx-ha-argocd
    targetRevision: HEAD
    path: app

  destination:
    server: https://kubernetes.default.svc
    namespace: web-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true